### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joseepoirier**
The map wouldn't display. Updated the URL.

### CODE REVIEW

**Comment by joseepoirier** [comment]
@turnerm Ok to merge this?

**Comment by turnerm** [comment]
Oh my gosh, so sorry I missed this somehow! In [the preview](https://github.com/OCHA-DAP/pa-anticipatory-action/blob/7f36842dbb7aa7a4199c8956615976969daf1a3d/README.md) the image is still broken for me. Are you sure you need both `[!image]`s?

**Comment by turnerm** [comment]
No changes from my end! But I'm so sorry, I still don't see the image... I can try to fix it next week

**Comment by joseepoirier** [comment]
Hmm. Weird. I wonder if it's because GH is referring to a "GH user" link instead of the original URL I supplied? That would be silly but it's strange that a public image doesn't show up for other uses in a public repo.

This isn't urgent. Was just trying to clean up open PRs and branches. 

Another thought: I wonder if Github now allows iframes in README's? If so we could embed the AA webpage map here so we don't have to sync up and update the two...

**Review by turnerm — APPROVED** [review]
@joseepoirier don't hate me but I just checked again because I was going to try to fix it, and it works for me now...

**Pull request merged**
